apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-management-dev
  template:
    metadata:
      labels:
        app: user-management-dev
    spec:
      containers:
      - name: user-management-dev
        image: benjaminucn/devops-taller-user-management:dev
        ports:
        - containerPort: 3001
